language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
# command to install dependencies
install: pip install -r tests/requirements.pip --use-mirrors
# command to run tests
script: python tests/manage.py test